export const apis = {
  // baseURL: "http://localhost:8686/",
  baseURL: "https://1a39-123-16-146-8.ap.ngrok.io",
  login: "api/public/nguoiDung/dangNhap",
  refresh_token: "api/public/token/refreshToken",
  get_list_reading_room: "api/resources/phongDoc/layDSPhongDoc",
  add_reading_room: "api/resources/phongDoc/themPhongDoc",
  edit_reading_room: "api/resources/phongDoc/suaPhongDoc",
  add_user: "api/resources/nguoiDung/themNguoiDung",
  edit_user: "api/resources/nguoiDung/suaNguoiDung",
  get_list_user: "api/resources/nguoiDung/layDSNguoiDung",
  get_ke_sach: "/api/resources/keSach/layDSKeSach",
  them_ke_sach: "/api/resources/keSach/themKeSach",
  edit_ke_sach: "api/resources/keSach/suaKeSach",
  get_tac_gia: "/api/resources/tacGia/layDSTacGia",
  add_tac_gia: "/api/resources/tacGia/themTacGia",
  edit_tac_gia: "/api/resources/tacGia/suaTacGia",
  get_sach: "/api/resources/keSach/layDSSach",
  add_sach: "/api/resources/keSach/themSach",
  edit_sach: "/api/resources/keSach/suaSach",
  lay_phong_doc_theo_ke_sach: "/api/resource/phongDoc/layPhongDocTheoKeSach",
  get_phieu_muon: "/api/resources/phieu/layDSPhieuMuonSach",
  get_phieu_tra: "/api/resources/phieu/layDSPhieuTraSach",
  add_phieu_muon: "/api/resources/phieu/taoPhieuMuonSach",
  add_phieu_tra: "/api/resources/phieu/taoPhieuTraSach",
};
